name: holo_mobile_coding_challenge
description: "Holo Mobile coding challenge e-commerce sample."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.3
  path_provider: ^2.1.3
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  go_router: ^14.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.2
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
